steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-west1-docker.pkg.dev/tidy-cortex-432423-m7/registro-imagen/payments-ms-prod',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-west1-docker.pkg.dev/tidy-cortex-432423-m7/registro-imagen/payments-ms-prod',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
